name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  tag:
    description: 'Docker image tag to use'
    required: true
  subdir:
    description: 'Subdirectory where code is cloned.'
    required: false
    default: "./"
  os: 
    description: 'OS to setup Docker for.'
    required: true
  distro:
    description: 'Distribution to setup Docker for.'
    required: true
  llvm:
    description: 'LLVM version to use.'
    required: false
    default: 15
  jdk:
    description: 'JDK version to use.'
    required: false
    default: 17
  dockerfile:
    description: 'Hardcode the path of the dockerfile to use.'
    required: false
    default: .github/workflows/Dockerfile
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    env:
      TAG_NAME: ${{ inputs.tag }}
      SUBDIR: ${{ inputs.subdir }}
      BASE_OS: ${{ inputs.os }}
      BASE_DISTRO: ${{ inputs.distro }}
      LLVM_VERSION: ${{ inputs.llvm }}
      JDK_VERSION: ${{ inputs.jdk }}
      DOCKERFILE: ${{ inputs.dockerfile }}
    run: |
      set -euxo pipefail

      Z3_VERSION=4.12.1
      K_COMMIT=$(cat deps/k_release)

      docker build .                           \
        --file .github/workflows/Dockerfile.z3 \
        --tag z3:${Z3_VERSION}                 \

      docker build . --file .github/workflows/Dockerfile \
        --tag runtimeverification/${TAG_NAME}            \
        --build-arg BASE_OS=${BASE_OS}                   \
        --build-arg BASE_DISTRO=${BASE_DISTRO}           \
        --build-arg K_COMMIT=${K_COMMIT}                 \
        --build-arg Z3_VERSION=${Z3_VERSION}             \
        --build-arg LLVM_VERSION=${LLVM_VERSION}

      docker run                        \
        --name ${TAG_NAME}              \
        --rm                            \
        --interactive                   \
        --tty                           \
        --detach                        \
        --user root                     \
        --workdir /home/user/workspace  \
        runtimeverification/${TAG_NAME}

      docker cp . ${TAG_NAME}:/home/user/workspace
      docker exec ${TAG_NAME} chown -R user:user /home/user
