name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  tag:
    description: 'Docker image tag to use'
    required: true
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    env:
      TAG_NAME: ${{ inputs.tag }}
    run: |
      set -euxo pipefail

      Z3_VERSION=4.12.1
      LLVM_VERSION=14
      K_COMMIT=$(cat deps/k_release)
      USER_ID=$(id -u)
      GROUP_ID=$(id -g)
      docker build .                           \
        --file .github/workflows/Dockerfile.z3 \
        --tag z3:${Z3_VERSION}                 \

      docker build . --file .github/workflows/Dockerfile \
        --tag runtimeverification/${TAG_NAME}            \
        --build-arg K_COMMIT=${K_COMMIT}                 \
        --build-arg Z3_VERSION=${Z3_VERSION}             \
        --build-arg LLVM_VERSION=${LLVM_VERSION}         \
        --build-arg USER_ID=${USER_ID}                   \
        --build-arg GROUP_ID=${GROUP_ID}

      docker run                        \
        --name ${TAG_NAME}              \
        --rm                            \
        --interactive                   \
        --tty                           \
        --detach                        \
        --user root                     \
        --workdir /home/user/workspace  \
        runtimeverification/${TAG_NAME}

      docker cp . ${TAG_NAME}:/home/user/workspace
      docker exec ${TAG_NAME} chown -R user:user /home/user
