name: 'Bump Version and Start Release Job'
on:
  push:
    branches:
      - 'master'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  version-bump:
    name: 'Version Bump'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          # fetch-depth 0 means deep clone the repo
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: 'Configure GitHub user'
        run: |
          git config user.name rv-jenkins
          git config user.email devops@runtimeverification.com
      - name: 'Update version'
        run: |
          set -x
          git checkout -B release origin/release
          old_master="$(git merge-base origin/master origin/release)"
          new_master="$(git rev-parse origin/master)"
          if git diff --exit-code ${old_master} ${new_master} -- package/version; then
            git merge --no-edit origin/master
            ./package/version.sh bump
          else
            git merge --no-edit --strategy-option=theirs origin/master
          fi
          ./package/version.sh sub
          if git add --update && git commit --no-edit --allow-empty --message "Set Version: $(cat package/version)"; then
            git push origin release
            git tag "release-$(cat package/version)" origin/master
            git push origin "release-$(cat package/version)"
          fi
