name: 'Master Push'
on:
  push:
    branches:
      - 'master'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  nix-cache:
    name: 'Populate Nix Cache'
    strategy:
      matrix:
        include:
          - runner: normal
          - runner: macos-13
          - runner: ARM64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.sha }}
          fetch-depth: 0
      - name: 'Upgrade bash'
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew install bash
      - name: 'Install Nix'
        if: ${{ matrix.runner == 'macos-13' }}
        uses: cachix/install-nix-action@v19
        with:
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: 'Install Cachix'
        if: ${{ matrix.runner == 'macos-13' }}
        uses: cachix/cachix-action@v12
        with:
          name: k-framework
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          skipPush: true
      - name: 'Build and cache KEVM'
        uses: workflow/nix-shell-action@v3.0.3
        env:
          GC_DONT_GC: 1
          CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
        with:
          packages: jq
          script: |
            kevm=$(nix build --extra-experimental-features 'nix-command flakes' .#kevm --json | jq -r '.[].outputs | to_entries[].value')
            drv=$(nix-store --query --deriver ${kevm})
            nix-store --query --requisites --include-outputs ${drv} | cachix push k-framework

  make-release:
    name: 'Cut Release'
    runs-on: ubuntu-latest
    needs: nix-cache
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.sha }}
          fetch-depth: 0
      - name: 'Make Release'
        env:
         GITHUB_TOKEN: ${{ secrets.JENKINS_GITHUB_PAT }}
        run: |
          set -x
          kevm_version=v$(cat package/version)
          gh release create "${kevm_version}" --target "${GITHUB_SHA}"

  gh-pages:
    name: 'Publish GH Pages'
    runs-on: ubuntu-latest
    needs: make-release
    steps:
      - name: 'Check out gh-pages'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.event.push.head.sha }}
      - run: |
         git config --global user.email 'devops@runtimeverification.com'
         git config --global user.name  'RV DevOps'
      - name: 'Publish gh-pages'
        run: |
          git checkout -B gh-pages
          cd web
          npm install
          npm run build
          npm run build-sitemap
          cd -
          mv web/public_content ./
          rm -rf $(find . -maxdepth 1 -not -name public_content -a -not -name .git -a -not -name .gitmodules -a -not -path . -a -not -path .. -a -not -name CNAME)
          mv public_content/* ./
          rm -rf public_content
          git add ./
          git commit -m 'gh-pages: Updated the website'
          git merge --strategy ours origin/gh-pages --allow-unrelated-histories
          git push origin gh-pages
      - name: 'Post failure to channel'
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "#kevm-notifications"
          slack-message: "Failed to create KEVM release: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: 'Post success to channel'
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "#kevm-notifications"
          slack-message: "Created KEVM release: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
