name: 'Master Push'
on:
  push:
    branches:
      - 'master'
      - 'docker-images'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  dockerhub-image:
    name: 'Build Ubuntu Jammy DockerHub Image'
    runs-on: [self-hosted, linux, normal]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ github.event.push.head.sha }}
      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          tag: kevm-package-jammy-${{ github.sha }}
      - name: 'Build Package'
        run: |
          set -euxo pipefail
          version=$(cat package/version)
          docker exec -u user kevm-package-jammy-${GITHUB_SHA} /bin/bash -c 'package/debian/package jammy'
          docker exec -u user kevm-package-jammy-${GITHUB_SHA} /bin/bash -c 'ls ..'
          docker cp kevm-package-jammy-${GITHUB_SHA}:/home/user/kevm_${version}_amd64.deb ./
      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 kevm-package-jammy-${GITHUB_SHA}
      - name: 'Build Docker Image'
        run: |
          set -euxo pipefail
          version=$(cat package/version)
          k_version=$(cat deps/k_release)
          tag_name="runtimeverificationinc/kevm:ubuntu-jammy-${version}"
          container_name="kevm-ci-test-${GITHUB_SHA}"
          docker build . --tag ${tag_name} --file package/docker/Dockerfile \
            --build-arg K_VERSION=${k_version}                              \
            --build-arg KEVM_VERSION=${version}
          docker run                 \
            --name ${container_name} \
            --rm                     \
            --interactive            \
            --tty                    \
            --detach                 \
            --user root              \
            --workdir /home/user     \
            ${tag_name}
      - name: 'Test Docker Image'
        run: |
          set -euxo pipefail
          version=$(cat package/version)
          k_version=$(cat deps/k_release)
          container_name="kevm-ci-test-${GITHUB_SHA}"
          docker cp ./tests/foundry ${container_name}:/home/user/foundry
          docker exec -u user ${container_name} /bin/bash -c "sudo chown user:user -R /home/user/foundry"
          docker exec -u user ${container_name} /bin/bash -c "forge build --root foundry"
          docker exec -u user ${container_name} /bin/bash -c "kevm foundry-kompile --foundry-project-root foundry --verbose"
          docker exec -u user ${container_name} /bin/bash -c "kevm foundry-prove --foundry-project-root foundry --verbose --test AssertTest.test_assert_true_branch"
          docker exec -u user ${container_name} /bin/bash -c "kevm foundry-show --foundry-project-root foundry --verbose AssertTest.test_assert_true_branch"
          docker exec -u user ${container_name} /bin/bash -c "kevm foundry-list --foundry-project-root foundry --verbose"
          docker stop --time=0 ${container_name}
      - name: 'Push Docker Image to DockerHub'
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          set -euxo pipefail
          version=$(cat package/version)
          k_version=$(cat deps/k_release)
          tag_name="runtimeverificationinc/kevm:ubuntu-jammy-${version}"
          docker login --username rvdockerhub --password ${DOCKERHUB_PASSWORD}
          docker image push ${tag_name}
