name: 'Update Version'
on:
  push:
    branches:
      - '_update-deps_runtimeverification_k'
  workflow_dispatch:
# Stop in progress workflows on the same branch and same workflow to use latest committed code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-pr:
    name: 'Update kevm_pyk Version'
    runs-on: [self-hosted, linux]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 'Update pyk Version'
        run: |
          cd deps/k
          git fetch origin 'refs/tags/*:refs/tags/*'
          K_COMMIT="$(git tag --points-at HEAD | cut --characters=2-)"
          cd ../..
          cat kevm_pyk/setup.cfg.tmpl | sed 's/\${K_COMMIT}/'"${K_COMMIT}"'/' > kevm_pyk/setup.cfg
          git config user.name devops
          git config user.email devops@runtimeverification.com
          git add kevm_pyk/setup.cfg
          git commit -m "kevm_pyk/setup.cfg: update version to ${K_COMMIT}" || true
          git push origin "HEAD:_update-deps_runtimeverification_k"
