name: 'Update Version'
on:
  pull_request:
  workflow_dispatch:
# Stop in progress workflows on the same branch and same workflow to use latest committed code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-pr:
    name: 'Test PR'
    runs-on: [self-hosted, linux]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 'Update pyk Version'
        run: |
          K_COMMIT="$(cd deps/k && git tag --points-at HEAD | cut --characters=2-)"
          ./kevm_pyk/set-version.sh ${K_COMMIT}
          git add kevm_pyk/setup.cfg
          ! git commit -m "kevm_pyk/setup.cfg: update version to ${K_COMMIT}" || git push
