name: 'Update Version'
on:
  push:
    branches:
      - '_update-deps_runtimeverification_k'
      - '_update-deps_runtimeverification_blockchain-k-plugin'
  workflow_dispatch:
# Stop in progress workflows on the same branch and same workflow to use latest committed code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-versions:
    name: 'Update K and kevm-pyk versions'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 'Set up Git'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
      - name: 'Update release tag'
        run: |
          cd deps/k && git fetch --tags && cd ../..
          K_VERSION="$(cd deps/k && git tag --points-at HEAD)"
          echo "${K_VERSION}" > deps/k_release
          if git add deps/k_release && git commit -m 'deps/k_release: update release file'; then
              git push
          fi
      - name: 'Install Nix'
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            substituters = http://cache.nixos.org https://cache.iog.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - name: 'Install Cachix'
        uses: cachix/cachix-action@v10
        with:
          name: runtimeverification
          extraPullNames: kore
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: 'Update nix flake inputs'
        run: |
          nix run .#update-from-submodules
          git add flake.lock
          git commit -m "sync flake.lock to submodules" || true
          git push
