name: 'Update Version'
on:
  pull_request:
  workflow_dispatch:
# Stop in progress workflows on the same branch and same workflow to use latest committed code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-kevm-pyk:
    name: 'Update kevm_pyk Version'
    runs-on: [self-hosted, linux]
    steps:
      - name: 'Update kevm_pyk Version'
        uses: actions/checkout@v3
        run: |
            ./kevm_pyk/set-version.sh
            git push
