name: 'Update Version'
on:
  push:
    branches:
      - '_update-deps_runtimeverification_k'
      - '_update-deps/runtimeverification/blockchain-k-plugin'
      - '_update-deps/runtimeverification/pyk'
  workflow_dispatch:
# Stop in progress workflows on the same branch and same workflow to use latest committed code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-versions:
    name: 'Update dependency versions'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
      - run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
      - name: 'Install Python3.10'
        run: |
          sudo apt-get install --yes software-properties-common
          sudo apt-add-repository ppa:deadsnakes/ppa
          sudo apt-get install --yes python3.10
      - name: 'Update K Release tag'
        run: |
          cd deps/k
          git fetch --tags
          cd -
          K_VERSION="$(cd deps/k && git tag --points-at HEAD)"
          echo "${K_VERSION}" > deps/k_release
          git add deps/k_release && git commit -m 'deps/k_release: update release file' || true
      - name: 'Update pyk Release tag'
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          pyk_version="$(cat deps/pyk_release)"
          sed -i 's!pyk = { git = "https://github.com/runtimeverification/pyk.git", tag="[v0-9\.]*" }!pyk = { git = "https://github.com/runtimeverification/pyk.git", tag="'${pyk_version}'" }!' kevm-pyk/pyproject.toml
          cd kevm-pyk
          poetry update
          cd -
          git add kevm-pyk/ && git commit -m 'kevm-pyk/: sync poetry files' || true
      - name: 'Update plugin release tag'
        run: |
          cd deps/plugin
          rev=$(git rev-parse HEAD)
          cd -
          echo ${rev} > deps/blockchain-k-plugin_release
          git add deps/blockchain-k-plugin_release && git commit -m 'deps/blockchain-k-plugin_release: update release file' || true
      - name: 'Install Nix/Cachix'
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: k-framework
          authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
      - name: 'Update nix flake inputs'
        run: |
          k_version=$(cat deps/k_release)
          bkp_version=$(cat deps/blockchain-k-plugin_release)
          pyk_version=$(cat deps/pyk_release)
          sed -i 's!    k-framework.url = "github:runtimeverification/k/[v0-9\.]*"!    k-framework.url = "github:runtimeverification/k/'"${k_version}"'"!' flake.nix
          sed -i 's!    blockchain-k-plugin.url = "github:runtimeverification/blockchain-k-plugin/[0-9a-f]*"!    blockchain-k-plugin.url = "github:runtimeverification/blockchain-k-plugin/'"${bkp_version}"'"!' flake.nix
          sed -i 's!    pyk.url = "github:runtimeverification/pyk/[v0-9\.]*"!    pyk.url = "github:runtimeverification/pyk/'"${pyk_version}"'"!' flake.nix
          nix run .#update-from-submodules
          nix flake update
          git add flake.nix flake.lock && git commit -m 'flake.{nix,lock}: update Nix derivations' || true
      - name: 'Push updates'
        run: git push
